### ISSUE TITLE
Missing dependencies in package.json

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-charts#3]
We are missing apparent dependencies in `package.json` like:
- `metal-component`
- `metal-state`

Also... is the `bootstrap` dependency really needed?
- Is it the base for the billboard css?
- Do we use its js?
- Is it for demo purposes?

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

This project was originally generated by the yeoman-generator which is where the bootstrap came from, so we can remove it.
