### ISSUE TITLE
Missing AreaChart helper?

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-charts#6]
One very common chart seems to be `AreaChart`, but we don't have a specific helper for it. Would it make sense?

**Comment by Robert-Frampton** [comment]
We definitely can, maybe we would want to add more specificity to the name? In billboard.js there is `area`, `area-spline`, and `area-step`. Maybe we could have `AreaLineChart`, `AreaSplineChart`, and `AreaStepChart` just to keep things descriptive.

**Comment by jbalsas** [comment]
Sounds good, maybe @julien can take of that 😉

**Comment by julien** [comment]
@jbalsas @Robert-Frampton yes sure I'll be glad to work on it

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @julien, was this actually implemented? Can we close this?

**Comment by Robert-Frampton** [comment]
Yep!
